In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digit=load_digits()
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,test_size=0.2)


In [5]:
model=LogisticRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9638888888888889

In [6]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9944444444444445

In [7]:
model1=RandomForestClassifier()
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

0.975

In [8]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [17]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [19]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9638888888888889

In [21]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9944444444444445

In [23]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9833333333333333

In [25]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)


In [47]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digit.data):
    x_train1,x_test1,y_train1,y_test1=digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=1000),x_train1,x_test1,y_train1,y_test1))
    scores_svm.append(get_score(SVC(),x_train1,x_test1,y_train1,y_test1))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train1,x_test1,y_train1,y_test1))

In [48]:
print(scores_l)

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]


In [49]:
print(scores_svm)

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]


In [50]:
print(scores_rf)

[0.9131886477462438, 0.9482470784641068, 0.9265442404006677]


In [57]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000),digit.data,digit.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [61]:
cross_val_score(SVC(),digit.data,digit.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [67]:
cross_val_score(RandomForestClassifier(n_estimators=15),digit.data,digit.target)

array([0.91666667, 0.87777778, 0.93871866, 0.94986072, 0.89972145])